# Lista de namespaces a serem criados. Executar uma vez para criar os namespaces e depois criar os demais itens
namespaces:
  - application
  - application-dev

# Lista de sufixos que ser√£o aplicados como zonas
nodeSelectorNS:
  - dev
  - hmg
  - prd

pvcsByNS:
  - namespace: application
    pvcname: pvc-teste
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClassName: crc-csi-hostpath-provisioner
